backend:
    build: ./apps/backend
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./apps/backend/.env

  frontend:
    build: ./apps/frontend
    ports:
      - '3001:3001'
    depends_on:
      - backend
    env_file:
      - ./apps/frontend/.env